[build]
  # Specify the command to build the project
  command = "npm run build"
  
  # Directory that contains the production files
  publish = "dist"

# Redirect all requests to index.html to support client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

